import { FunctionComponent, FC, NamedExoticComponent, ReactNode } from 'react';

declare interface AirModelInstance {
  [key: string]: any;
  [key: number]: any;
}

export declare type ModelContext = {
  memo: <M extends () => any>(call: M, deps: unknown[]) => ReturnType<M>;
  ref: <C>(current: C) => { current: C };
};

export declare type AirReducer = (state: any) => any;

declare type ValidInstanceRecord<S, T extends AirModelInstance> = {
  [K in keyof T]: T[K] extends (...args: any[]) => S
    ? T[K]
    : T[K] extends (...args: any[]) => any
    ? never
    : T[K];
};

declare type ValidInstance<S, T extends AirModelInstance> = ValidInstanceRecord<
  S,
  T
>;

declare type PickState<R extends AirReducer> = R extends (state: infer S) => any
  ? S
  : never;

/**
 * The validate model return type.
 */
declare type ValidReducerReturnType<R extends AirReducer> = R extends (
  state: infer S
) => infer T
  ? ValidInstance<S, T>
  : never;

// Check if the model is validated.
// The methods of model instance should return a same type with state.
declare type ValidReducer<R extends AirReducer> = R extends (
  state: infer S
) => infer T
  ? T extends ValidInstanceRecord<S, T>
    ? R
    : never
  : never;

// Check if the type of model function is validate.
// The methods of model instance should return a same type with state.
declare type ValidModel<R extends AirReducer> = R extends (
  state: infer S
) => infer T
  ? T extends ValidInstance<S, T>
    ? R
    : (state: S) => ValidInstance<S, T> & T
  : never;

declare type PipeCallback<S> = <R extends AirReducer>(
  modelFn: R
) => ValidReducer<R> & { getSourceFrom: () => any };

export declare type ModelKey<R extends AirReducer> = ValidReducer<R> & {
  pipe: PipeCallback<PickState<R>>;
  /**
   * @deprecated
   */
  effect?: [(...params: any[]) => any, Record<string, any>?];
  payload?: unknown;
  global: () => ModelKey<R>;
};

declare type SignalWatchMatcher<R extends AirReducer> = {
  /**
   * Add action methods for listening
   * @param actionMethods action methods for listening
   */
  on: (...actionMethods: ((...args: any[]) => any)[]) => SignalWatchMatcher<R>;
  /**
   * Add data change from instance for listening
   * @param comparator data change from instance for listening
   */
  of: (
    comparator: (instance: ValidReducerReturnType<R>) => any[]
  ) => SignalWatchMatcher<R>;
};

/**
 * It accepts a model key, returns the instance from store which is created by this model key.
 *
 * @param modelKey model key generated by `createKey`
 * @return instance in store generated by model key.
 *
 * Calling method from instance can generate a new state,
 * and useModel refreshes instance by calling model function with this new state.
 *
 * ex:
 *
 * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
 * * const modelKey = createKey(modelFn, 0);
 * * const instance = useModel(modelKey);
 * * const {count, increase} = instance;
 */
export declare function useModel<R extends AirReducer>(
  modelKey: ModelKey<R>
): ValidReducerReturnType<R>;
/**
 * It accepts a model function, returns an instance from this model function.
 *
 * @param modelFn model function
 * @return instance generated by model function.
 *
 * Calling method from instance can generate a new state,
 * and useModel refreshes instance by calling model function with this new state.
 *
 * ex:
 *
 * * const modelFn = (state:number|undefined = 0)=>({count:state, increase:()=>state+1});
 * * const instance = useModel(modelFn);
 * * const {count, increase} = instance;
 */
export declare function useModel<R extends AirReducer>(
  modelFn: R
): undefined extends PickState<R> ? ValidReducerReturnType<R> : never;
export declare function useModel<R extends AirReducer>(
  modelFn: R & { getSourceFrom: () => any }
): ValidReducerReturnType<R>;
/**
 * It accepts a model key and an initialized state, returns the instance from store which is created by this model key.
 *
 * @param modelKey model key generated by `createKey`
 * @param initializedState initialized state for render time initializing
 * @return instance in store generated by model key.
 *
 * Calling method from instance can generate a new state,
 * and useModel refreshes instance by calling model function with this new state.
 *
 * ex:
 *
 * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
 * * const modelKey = createKey(modelFn);
 * * const instance = useModel(modelKey, 0);
 * * const {count, increase} = instance;
 */
export declare function useModel<R extends AirReducer, D extends PickState<R>>(
  modelKey: ModelKey<R>,
  initializedState: D
): ValidReducerReturnType<R>;
/**
 * It accepts a model function and an initialized state, returns an instance from this model function.
 *
 * @param modelFn model function
 * @param initializedState initialized state
 * @return instance generated by model function.
 *
 * Calling method from instance can generate a new state,
 * and useModel refreshes instance by calling model function with this new state.
 *
 * ex:
 *
 * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
 * * const instance = useModel(modelFn, 0);
 * * const {count, increase} = instance;
 */
export declare function useModel<R extends AirReducer, D extends PickState<R>>(
  modelFn: R,
  initializedState: D
): ValidReducerReturnType<R>;
export declare function useModel<R extends AirReducer, D extends PickState<R>>(
  modelFn: R,
  initializedState?: D
): undefined extends PickState<R> ? ValidReducerReturnType<R> : never;

/**
 * The instance generator function returns by useSignal.
 *
 * ex:
 *
 * * const modelFn = (state:number|undefined = 0)=>({count:state, increase:()=>state+1});
 * * const generator = useSignal(modelFn);
 * * const {count, increase} = generator();
 *
 * @property watch A method for watching model state change
 * @property effect A method for doing effects about model state change
 */
export declare type SignalFunction<R extends AirReducer> =
  (() => ValidReducerReturnType<R>) & {
    watch: (watchCallback: () => void) => SignalWatchMatcher<R>;
    effect: (effectCallback: () => void) => SignalWatchMatcher<R>;
  };

/**
 * It accepts a model key, and return an instance generator callback from store.
 * That means you can get the latest instance by calling this generator in any place.
 *
 * Another difference with useModel is that the useSignal API can reduce render frequency
 * by comparing if the used fields data from generated instance have changed.
 *
 * @param modelKey model key generated by `createKey`.
 * @return A instance generator callback from store.
 *
 * ex:
 *
 * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
 * * const modelKey = createKey(modelFn);
 * * const generator = useSignal(modelKey);
 * * const {count, increase} = generator();
 */
export declare function useSignal<R extends AirReducer>(
  modelKey: ModelKey<R>
): SignalFunction<R>;
/**
 * It accepts a model function, and return an instance generator callback.
 * That means you can get the latest instance by calling this generator in any place.
 *
 * Another difference with useModel is that the useSignal API can reduce render frequency
 * by comparing if the used fields data from generated instance have changed.
 *
 * @param modelFn model function.
 * @return A instance generator callback.
 *
 * ex:
 *
 * * const modelFn = (state:number|undefined = 0)=>({count:state, increase:()=>state+1});
 * * const generator = useSignal(modelFn);
 * * const {count, increase} = generator();
 */
export declare function useSignal<R extends AirReducer>(
  modelFn: R
): undefined extends PickState<R> ? SignalFunction<R> : never;
export declare function useSignal<R extends AirReducer>(
  modelFn: R & { getSourceFrom: () => any }
): SignalFunction<R>;
/**
 * It accepts a model key and an initialized state, returns an instance generator callback from store.
 * That means you can get the latest instance by calling this generator in any place.
 *
 * Another difference with useModel is that the useSignal API can reduce render frequency
 * by comparing if the used fields data from generated instance have changed.
 *
 * @param modelKey model key generated by `createKey`.
 * @param initializedState initialized state for render time initializing.
 * @return A instance generator callback from store.
 *
 * ex:
 *
 * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
 * * const modelKey = createKey(modelFn);
 * * const generator = useSignal(modelKey, 0);
 * * const {count, increase} = generator();
 */
export declare function useSignal<R extends AirReducer, D extends PickState<R>>(
  modelKey: ModelKey<R>,
  initializedState: D
): SignalFunction<R>;
/**
 * It accepts a model function and an initialized state, returns an instance generator callback.
 * That means you can get the latest instance by calling this generator in any place.
 *
 * Another difference with useModel is that the useSignal API can reduce render frequency
 * by comparing if the used fields data from generated instance have changed.
 *
 * @param modelFn model function.
 * @param initializedState initialized state
 * @return A instance generator callback.
 *
 * ex:
 *
 * * const modelFn = (state:number|undefined = 0)=>({count:state, increase:()=>state+1});
 * * const generator = useSignal(modelFn, 0);
 * * const {count, increase} = generator();
 */
export declare function useSignal<R extends AirReducer, D extends PickState<R>>(
  modelFn: R,
  initializedState: D
): SignalFunction<R>;
export declare function useSignal<R extends AirReducer, D extends PickState<R>>(
  modelFn: R,
  initializedState?: D
): undefined extends PickState<R> ? SignalFunction<R> : never;

/**
 * It uses modelKey to link a store, and selects data from instance of this store.
 * When the selected data is changed, it renders component.
 *
 * @param modelKey model key
 * @param selector A callback accepts store instance object, and returns any data.
 * @param equalFn An optional callback for checking if data generated by selector is changed.
 * If it is not set, useSelector compares data change by using Object.is.
 */
export declare function useSelector<
  R extends AirReducer,
  C extends (instance: ValidReducerReturnType<R>) => any
>(
  modelKey: ModelKey<R>,
  selector: C,
  equalFn?: (c: ReturnType<C>, n: ReturnType<C>) => boolean
): ReturnType<C>;

/**
 * It accepts a model function, a state and a state change feedback function to link an outside state management,
 * returns an instance just like what useModel returns.
 * The difference with useModel is that useControlledModel has no state inside,
 * it is controlled by the outside one.
 *
 * @param modelFn model function
 * @param currentState state from outside state management
 * @param onStateChange state change feedback to outside state management
 */
export declare function useControlledModel<
  R extends AirReducer,
  D extends PickState<R>
>(
  modelFn: R,
  currentState: D,
  onStateChange: (changedState: PickState<R>) => any
): ValidReducerReturnType<R>;

/**
 * It is the collection of model keys type for Provider value property.
 * It can be an object or array.
 *
 * ex:
 *
 * * const modelKeys = {a: createKey(...), b: {c: createKey(...), d: createKey(...)}}
 * * const modelKeys = [createKey(...), {c: createKey(...), d: createKey(...)}];
 * * <Provider value={modelKeys}>...</Provider>
 */
export declare type ModelKeys =
  | {
      [key: string]: ModelKey<AirReducer> | ModelKeys | StoreApi<AirReducer>;
    }
  | {
      [key: number]: ModelKey<AirReducer> | ModelKeys | StoreApi<AirReducer>;
    }
  | ModelKey<AirReducer>
  | StoreApi<AirReducer>;

/**
 * It is a React.Context.Provider Component.
 * It transfers model keys or dynamic stores to Provider static stores,
 * and provide a Context scope for accessing these stores.
 *
 * @property value model keys or dynamic stores
 * @property key just value, choose one from 'key' or 'value' for setting model keys
 * @property children React nodes
 *
 */
export declare const Provider: FC<
  | {
      value: ModelKeys;
      children?: ReactNode;
    }
  | {
      keys: ModelKeys;
      children?: ReactNode;
    }
>;

/**
 * The config for optimizing state render process.
 */
export declare type GlobalConfig = {
  /**
   * Package `@airma/react-state` has no `react-dom` dependency,
   * and it dispatches action to every usage once,
   * that makes different components setState at one time.
   * Before react@18.0.0, the one time setState operations may cause component renders too many times.
   * With this option, you can set `unstable_batchedUpdates` from `react-dom` to it for an optimization.
   *
   * @param batchUpdateCallback ReactDom.unstable_batchedUpdates
   */
  batchUpdate?: (batchUpdateCallback: () => void) => void;
};

/**
 * It is a React.Context.Provider Component.
 * It can be used to optimize the state render process.
 *
 * @property value the optimize config
 * @property children the react nodes
 */
export declare const ConfigProvider: FC<{
  value: GlobalConfig;
  children?: ReactNode;
}>;

/**
 * The Hoc form for Provider Component
 * @param modelKeyOrStores model keys or dynamic stores
 * @return a callback accepts CustomizedComponent
 *
 * ex
 *
 * * const modelKey = createKey(...);
 * * const App = provide(modelKey)(CustomizedComponent);
 * * <App {...customizedProps}/>
 */
export declare function provide(
  modelKeyOrStores: ModelKeys
): <P extends Record<string, any>>(
  CustomizedComponent: FunctionComponent<P> | NamedExoticComponent<P>
) => typeof CustomizedComponent;

/**
 * It creates a model key from a model function.
 * Provide model key to Provider Component can create a Provider static store.
 *
 * @param modelFn model function
 * @param initializedState initialized state for store, it is optional
 * @return model key
 */
export declare function createKey<R extends AirReducer, D extends PickState<R>>(
  modelFn: R,
  initializedState?: D
): ModelKey<R>;

/**
 * It checks if two data is shallow equal.
 * @param data1
 * @param data2
 * @return Equal true, else false
 */
export declare function shallowEqual<R>(data1: R, data2: R): boolean;

/** model API * */

/**
 * Static store object
 */
declare interface StaticStoreApi<R extends AirReducer> {
  /**
   * It can accept an initialized state, and return the instance from store.
   *
   * @param initializedState initialized state for render time initializing.
   * @return instance in store generated by model function.
   *
   * Calling method from instance can generate a new state,
   * and useModel refreshes instance by calling model function with this new state.
   *
   * ex:
   *
   * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
   * * const store = model(modelFn).createStore();
   * * const instance = store.useModel(0);
   * * const {count, increase} = instance;
   */
  useModel: (initializedState?: PickState<R>) => ValidReducerReturnType<R>;
  /**
   * It can accept an initialized state, and return an instance generator callback from store.
   * That means you can get the latest instance by calling this generator in any place.
   *
   * Another difference with useModel is that the useSignal API can reduce render frequency
   * by comparing if the used fields data from generated instance have changed.
   *
   * @param initializedState initialized state for render time initializing.
   * @return A instance generator callback from store.
   *
   * ex:
   *
   * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
   * * const store = model(modelFn).createStore();
   * * const generator = store.useSignal(0);
   * * const {count, increase} = generator();
   */
  useSignal: (initializedState?: PickState<R>) => SignalFunction<R>;
  /**
   * It can select data from store instance.
   * When the selected data is changed, it renders component.
   *
   * @param selector A callback accepts store instance object, and returns any data.
   * @param equalFn An optional callback for checking if data generated by selector is changed.
   * If it is not set, useSelector compares data change by using Object.is.
   */
  useSelector: <C extends (instance: ReturnType<R>) => any>(
    selector: C,
    equalFn?: (c: ReturnType<C>, n: ReturnType<C>) => boolean
  ) => ReturnType<C>;
}

/**
 * Dynamic store object, it should be provided by Provider for activation before usage.
 * A dynamic store provided by different Providers can generate different static stores in Providers.
 */
declare interface StoreApi<R extends AirReducer> extends StaticStoreApi<R> {
  // The model key of store
  key: ModelKey<R>;
  /**
   * A dynamic store object can combine with other dynamic stores or model keys by using method with.
   *
   * @param otherStoreOrKeys Other dynamic stores or model keys.
   * @return a combined store
   */
  with: <M extends ModelKey<AirReducer>>(
    ...otherStoreOrKeys: ({ key: M } | M)[]
  ) => StoreApi<R>;
  /**
   * Create a static store in global. It is same with store.static method
   */
  asGlobal: () => StaticStoreApi<R>;
  /**
   * Create a static store in global.
   */
  static: () => StaticStoreApi<R>;
  /**
   * It can activate dynamic stores and generate a Provider Component to wrap the customized Component for a store usage.
   * @param CustomizedComponent A customized Component with store usage.
   * @return A wrapped Component for instead the customized Component.
   *
   * ex:
   *
   * * const store = model(modelFn).createStore(initState);
   * * store.provide()(CustomizedComponent);
   */
  provide: <P>() => (
    CustomizedComponent: FunctionComponent<P> | NamedExoticComponent<P>
  ) => typeof CustomizedComponent;
  /**
   * Same with store.provide(), but more directly usage.
   *
   * @param CustomizedComponent
   *
   * ex:
   *
   * * const store = model(modelFn).createStore(initState);
   * * store.provideTo(CustomizedComponent);
   *
   */
  provideTo: <P>(
    CustomizedComponent: FunctionComponent<P> | NamedExoticComponent<P>
  ) => typeof CustomizedComponent;
  /**
   * Provider Component for activating dynamic store.
   *
   * ex:
   *
   * * const store = model(modelFn).createStore(initState);
   * * ......
   * * const ModelProvider = store.Provider;
   * * return <ModelProvider>......</ModelProvider>
   */
  Provider: FC<{ children?: ReactNode }>;
}

declare interface Api<R extends AirReducer> {
  useModel: undefined extends PickState<R>
    ? /**
       * It accepts an initialized state, and returns an instance from model function.
       *
       * @param initializedState initialized state with same type with the parameter of model function
       * @return instance generated by model function.
       *
       * Calling method from instance can generate a new state,
       * and useModel refreshes instance by calling model function with this new state.
       *
       * ex:
       *
       * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
       * * const instance = model(modelFn).useModel(0);
       * * const {count, increase} = instance;
       */
      (initializedState?: PickState<R>) => ValidReducerReturnType<R>
    : /**
       * It accepts an initialized state, and returns an instance from model function.
       *
       * @param initializedState initialized state with same type with the parameter of model function
       * @return instance generated by model function.
       *
       * Calling method from instance can generate a new state,
       * and useModel refreshes instance by calling model function with this new state.
       *
       * ex:
       *
       * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
       * * const instance = model(modelFn).useModel(0);
       * * const {count, increase} = instance;
       */
      (initializedState: PickState<R>) => ValidReducerReturnType<R>;
  useSignal: undefined extends PickState<R>
    ? /**
       * It accepts an initialized state, and returns an instance generator callback from model function.
       * That means you can get the latest instance by calling this generator in any place.
       *
       * Another difference with useModel is that the useSignal API can reduce render frequency
       * by comparing if the used fields data from generated instance have changed.
       *
       * @param initializedState initialized state
       * @return A instance generator callback.
       *
       * ex:
       *
       * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
       * * const generator = model(modelFn).useSignal(0);
       * * const {count, increase} = generator();
       */
      (initializedState?: PickState<R>) => SignalFunction<R>
    : /**
       * It accepts an initialized state, and returns an instance generator callback from model function.
       * That means you can get the latest instance by calling this generator in any place.
       *
       * Another difference with useModel is that the useSignal API can reduce render frequency
       * by comparing if the used fields data from generated instance have changed.
       *
       * @param initializedState initialized state
       * @return A instance generator callback.
       *
       * ex:
       *
       * * const modelFn = (state:number)=>({count:state, increase:()=>state+1});
       * * const generator = model(modelFn).useSignal(0);
       * * const {count, increase} = generator();
       */
      (initializedState: PickState<R>) => SignalFunction<R>;
  /**
   * It accepts a state and a state change feedback function to link an outside state management,
   * returns an instance just like what useModel returns.
   * The difference with useModel is that useControlledModel has no state inside,
   * it is controlled by the outside one.
   *
   * @param currentState state from outside state management
   * @param onStateChange state change feedback to outside state management
   */
  useControlledModel: (
    currentState: PickState<R>,
    onStateChange: (changedState: PickState<R>) => any
  ) => ValidReducerReturnType<R>;
  /**
   * Same as createStore
   *
   * @deprecated
   * @param state
   */
  store: (initializedState?: PickState<R>) => StoreApi<R>;
  /**
   * It can create a dynamic store object,
   * provide this dynamic store to Provider can activate this store,
   * and the useModel/useSelector/useSignal API from store can be used in the scope of store Provider.
   *
   * @param initializedState
   */
  createStore: (initializedState?: PickState<R>) => StoreApi<R>;
}

export declare const model: {
  /**
   * Declare a model
   * @param modelFn A model function
   * @return A validate wrapped model function with model APIs from parameter
   *
   * The declared model function has hook and store APIs with it.
   *
   * ex:
   *
   * * model(modelFn).useModel(initializedState?);
   * * model(modelFn).useSignal(initializedState?);
   * * const dynamicStore = model(modelFn).createStore(initializedState?);
   *
   * // Dynamic store is for Provider scope, it need provide to Component.
   *
   * * dynamicStore.provideTo(CustomizedComponent);
   * * dynamicStore.with(...otherStores).provideTo(CustomizedComponent);
   * * dynamicStore.useModel(initializedState?);
   * * dynamicStore.useSignal(initializedState?);
   *
   * // Static store is global, it needn't provide to Component.
   *
   * * const staticStore = dynamicStore.static();
   * * staticStore.useModel(initializedState?);
   * * staticStore.useSignal(initializedState?);
   */
  <R extends AirReducer>(modelFn: ValidModel<R>): R & Api<R>;
  /**
   * @deprecated
   */
  context: () => ModelContext;
  /**
   * If model is not a good name for you, use `model.create(modelFn)` to instead it.
   * @param modelFn
   */
  create: <M extends AirReducer>(modelFn: ValidModel<M>) => M & Api<M>;
};
